name: Run API Data Collection with Python Scripts Daily

on:
  schedule:
    - cron: '0 15 * * *'  # Daily at 06:00 UTC (07:00 local time)
  workflow_dispatch:  # allow manual workflow run

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # allow workflow to write to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: assets/API/
      run: |
        pip install -r requirements.txt

    - name: Run Global Data Collection
      working-directory: assets/API/
      run: |
        python 01_API_Load_IMIS_Daily_Data.py

    - name: Run Snow Data Collection
      working-directory: assets/API/
      run: |
        python 02_API_Load_IMIS_Daily_Snow.py

    # Commit and push changes to repository
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add assets/API/daily/04_SLF_daily_imis_measurements.csv
        git add assets/API/daily/05_SLF_daily_imis_snow.csv
        git commit -m "New Data Collection from API"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
