name: Run Merge of all daily live data

on:
  schedule:
    - cron: '30 06 * * *'  # Daily at 06:30 UTC (07:30 local time)
  workflow_dispatch:  # allow manual workflow run

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # allow workflow to write to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: assets/API/
      run: |
        pip install -r requirements.txt

    - name: Run Merge of all daily live data
      working-directory: assets/API/
      run: |
        python 05_Prepare_live_data_for_PCA.py

    # Commit and push changes to repository
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add assets/API/daily/06_SLF_daily_imis_all_live_data.csv
        git commit -m "Merged daily CSV files with all live data"
        git push  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
